Contact me form
MattGomb/Portfolio-project pull request #4
Opened 2022-08-23 21:17 UTC by MattGomb

Created the last part of the mobile version by:

- adding a new grid element that is the last 'page', the contact-me form
- adding the background
- adding the form
- styling the form
- styling the whole element to scale and fit into the project

2022-08-23 21:21 UTC, bobb-Rob commented
@MattGomb Please fix the linter issues on the style file

2022-08-23 22:02 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @MattGomb , 

Good job so far! 👏👏👏 
You did excellently well implementing the requirements in this project, but there are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 01:05 UTC, MattGomb commented
@bobb-Rob  hi, thank you for the suggestions, they are fixed now! :)

2022-08-24 01:35 UTC, franclobo requested changes
Hi @MattGomb , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Correct Github Flow 💯 
- Descriptive PR ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 01:35 UTC, franclobo commented on styles.css
> +  text-align: justify;
- [ ] **[OPTIONAL]** Kindly use `text-align: center` to stick to the design as much as possible. 📑 

![text-center](https://user-images.githubusercontent.com/58642949/186297570-e52e726a-a31a-4cdc-b7b7-9d79ada325f4.png)

2022-08-24 01:35 UTC, franclobo commented on styles.css
> +  outline: auto;
- [ ] **[OPTIONAL]** Please, 🙏🏽 we could avoid using `outline: auto` to delete the border around elements.

- With outline

![With-outline](https://user-images.githubusercontent.com/58642949/186296877-332948a9-18b4-490d-a6b8-aef6a9fe40c2.png)

- Without outline

![Without-outline](https://user-images.githubusercontent.com/58642949/186296914-d037b4fb-2457-4aaa-863a-8438f1347096.png)

2022-08-24 01:40 UTC, MattGomb commented
@franclobo thank you for the suggestions, fixed :)

2022-08-24 01:44 UTC, Reem-lab approved these changes
# Hi @MattGomb, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>


## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the design✅
📌 Good commit messages ✅
📌Professional README file. ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 02:06 UTC, merged